services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
    web:
        build: ./frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
    nginx: 
        build: ./infra
        ports:
            - "80:80"
        depends_on:
            - web